### ISSUE TITLE
Adding a CNI plugin in the chain

### ISSUE THREAD

**Issue by karampok** [cloudfoundry/cf-networking-release#25]
Greetings,
I am trying to create a PoC which requires to add another CNI plugin between the CF Wrapper plugin and the Slik CNI plugin. In theory, it should be supported by CNI spec since version 0.5.
I would like to have something like [that](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap), but I am not sure how it can be integrated.

My questions are:
Which version of the CNI spec is supported?
Any thoughts how I can add a binary CNI plugin by keeping everything else in place?

Thank you in advance
Konstantinos

**Comment by chinangela** [comment]
Hi,

We currently support v0.3.1 of the spec. I believe we would want to [update the garden-external-networker](https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/garden-external-networker/cni/cni_controller.go#L44) to use `AddNetworkList` instead of `AddNetwork`.

Of course, to actually use multiple plugins, you would need to provide the correct config, which would require additional changes.

If that answers your questions, let me know and I'll close the issue. Otherwise, happy to chat further.

Cheers,
Angela

**Comment by karampok** [comment]
Hi Angela, thanks for the reply.

Is there any plan of officially updating the cf-networking release to a latest version of the CNI? the version 0.5 has been released since around March. 

I do not see also how the correct config will look in order the extra binary to be called after cni-wrapper and before silk. There might be some hardcoded changes in the cni-wrapper in order to accomplish that as it is know (to my understanding).

I would prefer the issue to stay opened until CNI version 6. Just to be a story in backlog for this  request. Unless of course there are already stories for that.

Best,
Konstantinos

**Comment by chinangela** [comment]
Hi Konstantinos,

There is a plan to update to v0.6.0. However, the current version we are on is v0.5.2 of the CNI release, which supports the latest spec version (v0.3.1). The CNI release version doesn't really matter-- what matters is the CNI spec version.

`AddNetworkList` should take care of the chaining. Is the requirement that you want something in between invoking the CNI wrapper plugin and the Silk CNI? Or do you just need the results of the CNI wrapper plugin?

Cheers,
Angela

**Comment by karampok** [comment]
Okay, I think I am confused between CNI release and CNI-spec release. I am also not sure if chaining is part of the CNI-spec or not.

Actually I need both, something that runs before silk, so it can get the runtime-metadata, and something that will run after so it will make use of the IP returned by silk. There is no strong requirement, I am investigated what kind of flexibility I have in terms of injecting CNI plugins in the chain.  Does that make sense?

**Comment by chinangela** [comment]
Chaining isn't something that is required by CNI spec, but it is something that was introduced in v0.3.0 and we can use.

When you say "run before silk", does that mean between the CNI wrapper plugin writing the iptables rules and invoking the silk cni plugin, or would it be fine to run a plugin before calling the CNI wrapper plugin?

If it's the latter case, changes to call `AddNetworkList` instead of `AddNetwork` in the garden-external-networker would be sufficient. If its the former, then changes may need to be made to the CNI wrapper plugin.

**Comment by karampok** [comment]
I will try the case "will run at the end", so the order will be  `cniwrapper->silk-> customPlugin `.
I am going to switch to `AddNetworkList` and try manually use the chain config as it is described here [link](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) 

Let you know how it looks.

**Comment by karampok** [comment]
Modification to garden-external-networker are straightforward. Nevertheless the rest of the system does not want to work.

Do you think that you are going to update the containernetworking dependencies (plugin, cni) any time soon?

Among other errors,  I am getting an error like that
```
{
    "code": 100,
    "msg": "run ipam plugin",
    "details": "invalid range set 0: gateway 169.254.0.1 not in network 10.255.38.0/24"
}
```
which I think is because I am using  latest commit on this repos.

Thanks

**Comment by chinangela** [comment]
Hi,

We can add a chore to our backlog to update the dependencies, but I'm not sure when they would be prioritized.

Is it possible to run with the version of the repos that we run with? Or do you need some of the new features for the other plugins?

Cheers,
Angela

**Comment by karampok** [comment]
Hi, I am afraid it is not an option to work with an old version of the CNI codebase.
About a chore to update, it would be nice, and in my opinion, it might be a good idea to keep things updated. 

I suggest that we can close this issue and that you create another chore in the backlog to update the documentation about how a person can integrate a 3rd party cni plugin. 

Thanks for the help
