### ISSUE TITLE
question

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/cf-networking-release#41]
Hi, in the list of releases of cf-networking-release I see:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/27818611/40853053-f6544864-65cc-11e8-94f2-7f755c52ec96.png">

Could you please tell me the difference between the content of:

cf-networking-2.3.0.tgz
and 
Source code (zip) / Source code (tar.gz) ?

Thanks!

**Comment by christianang** [comment]
Hi @luisapace,

The `cf-networking-2.3.0.tgz` is the bosh release in a tarball e.g you could `bosh upload-release cf-networking-2.3.0.tgz` if you wanted to do that instead of using what is on bosh.io.

The source code is just the code and that is automatically created by GitHub.

Feel free to reopen if you have other questions.

**Comment by luisapace** [comment]
thanks! 
I've another question: does the cf-networking-2.3.0.tgz include all dependencies needed to run it? I mean compile and runtime dependencies; does it include all of them or only compile dependencies?
Thanks again.

**Comment by christianang** [comment]
When you use the bosh release it will download additional blobs from our blobstore, but any other code dependencies are included.

**Comment by luisapace** [comment]
Thanks a lot Christian.
