### ISSUE TITLE
could not access the app from the diego cell host vm which the app are running on.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/cf-networking-release#43]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

I'm trying to access the apps on the diego-cell which the app containers running.
say I'm trying to access
10.0.16.5:61000, 10.0.16.5 is the diego-cell eth0's ip, the diego-cell host ip.
and the "10.255.74.3" is the ip of the container.

but from other node in the same subnet, say, a vm with ip 10.0.16.4.
i can wget 10.0.16.5:61000.
seems the ip:port could not been accessed only in the containers are running on.

could you please help?

BTW, the 61000 is from the router config:
  "game-2048.20.189.129.209.xip.io": [
    {
      "address": "10.0.16.5:61000",
      "tls": false,
      "ttl": 120,
      "tags": {
        "component": "route-emitter"
      },
      "private_instance_id": "192e60cd-4404-42d3-6e87-404d",
      "server_cert_domain_san": "192e60cd-4404-42d3-6e87-404d"
    }
  ],
## Context

[provide more detailed introduction]

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

[include relevant logs]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by christianang** [comment]
Hi @andyliuliming,

If you want to access the app from a cell you should be using the container ip `10.255.74.3:<container-port>`.

The `10.0.16.5:61000` is for outside traffic (usually from the router) and the reason why this isn't working when you are on the same cell is because it is actually a DNAT itpables rule, where the DNAT rule says any traffic incoming and is destined for `10.0.16.5:61000` will be DNAT'd to `10.255.74.3:<container-port>`. When you make a request from the same cell it skips `PREROUTING` itpables rules which is where the DNAT rules are.

**Comment by andyliuliming** [comment]
Hi @christianang thanks for the explanation.
is there any configuration change I can made on the cell to make I can use 
10.0.16.5:61000 address to access the app?

**Comment by christianang** [comment]
Because of the way the iptables process flow is, a PREROUTING rule will not work on locally created requests, they only work on outside requests and changing it from PREROUTING would be a significant change and I'm not entirely sure if it would work because POSTROUTING might be too late in the process.

Can I ask what is your use case for using `10.0.16.5:61000` instead of the container ip and port?

**Comment by XanderStrike** [comment]
Closed due to inactivity.
