### ISSUE TITLE
space_developer_test intermittently failing in 2.7

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/cf-networking-release#69]
## Issue

Intermittent failure of space_developer_test during 2.7 deployments.

We are filing an issue to make your team aware of these failures.

## Context

PAS Releng team has seen a number of failed pnats runs with the same symptoms.

```
[2019-06-10 17:35:36.34 (UTC)]> cf curl -X PUT /v2/organizations/b5039dc7-ddac-402c-a5f8-06dfcaa31feb/users/space-client 

[2019-06-10 17:35:36.34 (UTC)]> cf curl -X PUT /v2/spaces/3478947b-e2bc-4db9-955b-aef70fca758d/developers/space-client 

[2019-06-10 17:35:36.35 (UTC)]> cf curl -X PUT /v2/spaces/56fd688d-18e9-4ad8-a8c8-cdc25acc386d/developers/space-client 
STEP: logging in and getting the space developer user token

[2019-06-10 17:35:36.35 (UTC)]> cf auth space-client password --client-credentials 
API endpoint: https://api.sys.vivid-fancier.gcp.releng.cf-app.com
Authenticating...
{
   "description": "space-client",
   "error_code": "CF-InvalidRelation",
   "code": 1002
}
```

## Steps to Reproduce

Happens randomly while running pnats.

## Expected result

test to pass successfully.

## Current result

```
• Failure [73.906 seconds]
space developer policy configuration
/tmp/build/29505db7/acceptance-tests/src/test/acceptance/space_developer_test.go:23
  space developer with network.write scope
  /tmp/build/29505db7/acceptance-tests/src/test/acceptance/space_developer_test.go:125
    can create, list, and delete network policies in spaces they have access to
    /tmp/build/29505db7/acceptance-tests/src/github.com/onsi/ginkgo/extensions/table/table.go:92
      as a service account [It]
      /tmp/build/29505db7/acceptance-tests/src/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

      Expected
          <int>: 1
      to match exit code:
          <int>: 0

      /tmp/build/29505db7/acceptance-tests/src/test/acceptance/space_developer_test.go:143
```

**Comment by syslxg** [comment]
We've looked into this issue a bit further and found the lines that [trigger the issue](https://github.com/cloudfoundry/cf-networking-release/blob/5b3cee63bba51d8579911b1d0a428d66a586d29f/src/test/acceptance/space_developer_test.go#L107-L109). It appears that the `cf.Cf` sessions are not being checked prior to proceeding to the next `cf` execution, and for whatever reason the first `cf.Cf` is returning the following error:
```json
{
   "description": "space-client",
   "error_code": "CF-InvalidRelation",
   "code": 1002
}
```
Because the `space-client` is not being set as an `org-user`, the `space-client` cannot target the org and is failing to proceed.

The 3 `cf curl` calls should have their sessions checked for a successful response prior to proceeding. Also, is there any reason you cannot use `cf set-org-role`/`cf set-space-role` instead of manually `curl`ing these endpoints?

**Comment by syslxg** [comment]
Here's an instance of these tests failing in our pipeline:
https://releng.ci.cf-app.com/teams/main/pipelines/ert::2.7/jobs/run-nats-gcp-clean/builds/23

**Comment by XenoPhex** [comment]
Note: This is happening on older releases as well (we had several 2.5 test pipelines fail as well).

**Comment by KauzClay** [comment]
Hi @markstokan , I believe we have seen this ourselves, and I thought we addressed it with this [commit](https://github.com/cloudfoundry/cf-networking-release/commit/41d73f93cac4b687a3b6c4e76534bf2e3b08dadf). This should be in the most recent release we just cut last week, 2.23.

Anyway, from what we saw, the problem was that by having them all run right after the other, sometimes `cf.Cf("curl", "-X", "PUT", fmt.Sprintf("/v2/organizations/%s/users/space-client", orgGuid))` wouldn't happen before the next two, so the calls with spaceGuid would fail because the org role didn't exist yet. We resolved it by just making the orgGuid PUT call run and finish first before the space ones. That has fixed the problem for us, but please let us know if it doesn't resolve it for you.

@syslxg , as for why we curl the endpoints instead of using `set-org-role` and `set-space-role`, I'm not sure why. Maybe we can look into changing that as well

**Comment by rizwanreza** [comment]
@KauzClay You can close this issue now.
